# Generated by Django 6.0.3 on 2026-03-09 10:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(default='Hindi', max_length=50)),
                ('craft_type', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True, help_text='AI-generated or manual artisan biography')),
                ('story', models.TextField(blank=True, help_text="The artisan's personal craft story")),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='artisans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('cultural_story', models.TextField(blank=True, help_text='AI-generated heritage/cultural context')),
                ('category', models.CharField(choices=[('painting', 'Painting'), ('textile', 'Textile & Weaving'), ('pottery', 'Pottery & Ceramics'), ('jewelry', 'Jewelry'), ('woodwork', 'Woodwork & Carving'), ('metalwork', 'Metalwork'), ('embroidery', 'Embroidery'), ('sculpture', 'Sculpture'), ('basketry', 'Basketry'), ('leatherwork', 'Leatherwork'), ('other', 'Other')], default='other', max_length=50)),
                ('art_form', models.CharField(blank=True, help_text='e.g. Madhubani, Bidri, Phulkari', max_length=200)),
                ('materials', models.CharField(blank=True, max_length=500)),
                ('techniques', models.CharField(blank=True, max_length=500)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('suggested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated SEO tags', max_length=500)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.artisan')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('instagram', 'Instagram Post'), ('facebook', 'Facebook Post'), ('product_desc', 'Product Description'), ('campaign', 'Campaign Idea'), ('hashtags', 'Hashtags')], max_length=50)),
                ('content', models.TextField()),
                ('language', models.CharField(default='English', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_contents', to='core.product')),
            ],
        ),
    ]
