# Generated by Django 6.0.3 on 2026-03-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='artisan',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
